### ISSUE TITLE
show error when "php composer.phar install"

### ISSUE THREAD

**Issue by jianfengye** [researchgate/broker#27]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/console 2.1.x-dev
    - Conclusion: don't install symfony/console 2.8.x-dev
    - Conclusion: don't install symfony/console v2.1.13
    - Conclusion: don't install symfony/console 2.7.x-dev
    - Conclusion: don't install symfony/console v2.1.12
    - Installation request for composer/composer dev-master -> satisfiable by composer/composer[dev-master].
    - Can only install one of: symfony/console[v2.1.0, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.1, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.10, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.11, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.2, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.3, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.4, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.5, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.6, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.7, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.8, 2.5.x-dev].
    - Can only install one of: symfony/console[v2.1.9, 2.5.x-dev].
    - composer/composer dev-master requires symfony/console ~2.5 -> satisfiable by symfony/console[2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev].
    - Conclusion: don't install symfony/console 2.6.x-dev
    - Installation request for symfony/console 2.1.* -> satisfiable by symfony/console[2.1.x-dev, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9].

**Comment by bashofmann** [comment]
As the README states: This project is not actively maintained anymore. Since satis supports a similar functionality now, you should use satis instead.

Feel free to fix this and send a pull request though

**Comment by jianfengye** [comment]
Thanks, I use satis instead.
